version: '3'

services:
   db:
     image: postgres:11.4
     volumes:
       - db_data:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: secret
       POSTGRES_DB: drupal
       POSTGRES_USER: dp_user
     networks:
       - dp_network

   drupal:
     depends_on:
       - db
     image: drupal
     ports:
       - "80:80"
     volumes:
       - drupal_modules:/var/www/html/modules
       - drupal_profiles:/var/www/html/profiles
       - drupal_themes:/var/www/html/themes
       - drupal_sites:/var/www/html/sites
     networks:
       - dp_network

   adminer:
     depends_on:
       - db
     image: adminer
     ports:
       - "8080:8080"
     networks:
       - dp_network

   swissarmyknife:
     image: bletvaska/swissarmyknife
     networks:
       - dp_network 
     

volumes:
    drupal_modules:
    drupal_profiles:
    drupal_themes:
    drupal_sites:
    db_data: {}
networks:
    dp_network:
