apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: adminer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: adminer
    spec:
      containers:
      - image: adminer
        name: adminer
        ports:
        - containerPort: 8080
        resources: {}
status: {}
