apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: wp-db
    tier: backend
    env: prod
    customer: tuke
  name: wp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wp-db
  template:
    metadata:
      labels:
        run: wp-db
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: wp_user
        - name: MYSQL_PASSWORD
          value: end321
        - name: MYSQL_DATABASE
          value: wordpress
        image: mariadb
        name: wp-db
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: wp-db
  name: wp-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: wp-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: wp-app
    tier: frontend
    env: prod
    customer: tuke
  name: wp-app
spec:
  replicas: 4 
  selector:
    matchLabels:
      run: wp-app
  template:
    metadata:
      labels:
        run: wp-app
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: wp-db
        - name: WORDPRESS_DB_USER
          value: wp_user
        - name: WORDPRESS_DB_PASSWORD
          value: end321
        - name: WORDPRESS_DB_NAME
          value: wordpress
        image: wordpress
        name: wp-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: wp-app
  name: wp-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wp-app
  type: LoadBalancer
