version: '3.3'

services:
   db:
     image: mysql
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: wp
       MYSQL_USER: wp_user
       MYSQL_PASSWORD: start123
     networks:
       - wp_network

   wordpress:
     depends_on:
       - db
     image: wordpress
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wp_user
       WORDPRESS_DB_PASSWORD: start123 
       WORDPRESS_DB_NAME: wp
     networks:
       - wp_network

   adminer:
     depends_on:
       - db
     image: adminer
     ports:
       - "8080:8080"
     networks:
       - wp_network

volumes:
    db_data: {}
networks:
    wp_network:
